### PR TITLE
Added another fn to perform typing and sending to clipboard together.

### PR DESCRIPTION
**Pull request by niksingh710**
This will give the user a choice to have the emoji in the clipboard and typed at the same time.

(helpful for someone like me who uses vim and forgets that he is in normal mode and selects emoji to just realize that it has not been written so I prefer to get that to my clipboard too)

### CODE REVIEW

**Comment by marty-oehme** [comment]
I like the idea of the PR but I think it should not be an additional commabdline option.

We already have and option `-t` for typing and `-c` for clipping and could just use both to do both actions, which I feel would be more natural.
 
Currently on vacation but can take a closer look over it in a week or two.

**Comment by niksingh710** [comment]
I have tried to merge `-c` and `-t` together to achieve this result but that does not seem to follow the way the whole code is structured.
As I have noticed I felt like `-c` is  a redundant flag because it is the default behavior if no flag is provided,
so I guess having `-t` and only `-b` is a better approach.
Tell me what you think about That.

**Comment by marty-oehme** [comment]
Hey, I finally have a little time again to look over things. 

The `-c` option is necessary in case somebody wants to clip the results but overwrote the default behavior with the `BEMOJI_DEFAULT_CMD` environment variable. Otherwise, there is no way to send the results to clipboard anymore.

I am also not super happy with the redundancy of `-t` and `-b` - First, it adds another cli option of which the program already has quite a few for the simple thing it does, and second if we are already allowing multiple commands to be executed at once, why not extend it to `-e` (echo the results) as well? 

I still think just allowing `-t`, `-c` and `-e` to be combined is the way to go. I looked over the code a little earlier and believe I've found a way to make it work without too much hassle, will prepare a commit in a bit.

**Comment by niksingh710** [comment]
I merging the CLI flags is possible then ig I should close the pr.

**Pull request closed without merging**
